[tool.black]
line-length = 79
include = '\.pyi?$'
skip-string-normalization = true

exclude = '''(
    /(
        \.eggs    # exclude a few common directories in the
      | \.git     # root of the project
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | migrations
      | venv
      | tests
    )/
    | foo.py  # exclude a single file
    | bar/
)'''
